print('How many items will you use to craft something (type number 2-4)')
howitem = input()

if howitem == "2":
    print('First item id:')
    fi = input()
    print('')
    print('First item quantity')
    fc = input()
    print('')
    print('First item nbt (optional):')
    fn = input()
    print('')
    print('Second item id:')
    si = input()
    print('')
    print('Second item quantity')
    sc = input()
    print('')
    print('Second item nbt (optional):')
    sn = input()
    print('')
    print('Crafted item id:')
    ci = input()
    print('')
    print('Crafted item quantity')
    cc = input()
    print('')
    print('Crafted item nbt (optional):')
    cn = input()
    print('')
    print('')
    print('')
    if fn != "":
        fn = ',tag:' + fn
    if sn != "":
        sn = ',tag:' + sn
    if cn != "":
        cn = ',tag:' + cn
    print('')
    print('')
    print('')
    print('')
    print('First command:')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] run summon item ~ ~ ~ {Item:{id:"minecraft:' + ci + '",Count:' + cc + 'b' + cn + '}}')
    print('')
    print('Second command (particles):')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] run particle minecraft:cloud ~ ~ ~ 0 0 0 0.1 100')
    print('')
    print('Third command:')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] run kill @e[type=item,distance=..1,nbt=!{Item:{id:"minecraft:' + ci +'",Count:' + cc + 'b' + cn + '}}] ')
    print('')
    print('Custom command (optional):')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] run (YOUR COMMAND HERE)')
    print('')
    print('')
    print('')
    print('')
    input()

if howitem == "3":
    print('First item id:')
    fi = input()
    print('')
    print('First item quantity')
    fc = input()
    print('')
    print('First item nbt (optional):')
    fn = input()
    print('')
    print('Second item id:')
    si = input()
    print('')
    print('Second item quantity')
    sc = input()
    print('')
    print('Second item nbt (optional):')
    sn = input()
    print('')
    print('Third item id:')
    ti = input()
    print('')
    print('Third item quantity')
    tc = input()
    print('')
    print('Third item nbt (optional):')
    tn = input()
    print('')
    print('Crafted item id:')
    ci = input()
    print('')
    print('Crafted item quantity')
    cc = input()
    print('')
    print('Crafted item nbt (optional):')
    cn = input()
    print('')
    print('')
    print('')
    if fn != "":
        fn = ',tag:' + fn
    if sn != "":
        sn = ',tag:' + sn
    if tn != "":
        tn = ',tag:' + tn
    if cn != "":
        cn = ',tag:' + cn
    print('')
    print('')
    print('')
    print('')
    print('First command:')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + ti +'",Count:' + tc + 'b' + tn + '}}] run summon item ~ ~ ~ {Item:{id:"minecraft:' + ci + '",Count:' + cc + 'b' + cn + '}}')
    print('')
    print('Second command (particles):')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + ti +'",Count:' + tc + 'b' + tn + '}}] run particle minecraft:cloud ~ ~ ~ 0 0 0 0.1 100')
    print('')
    print('Third command:')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + ti +'",Count:' + tc + 'b' + tn + '}}] run kill @e[type=item,distance=..1,nbt=!{Item:{id:"minecraft:' + ci +'",Count:' + cc + 'b' + cn + '}}] ')
    print('')
    print('Custom command (optional):')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + ti +'",Count:' + tc + 'b' + tn + '}}] run (YOUR COMMAND HERE)')
    print('')
    print('')
    print('')
    print('')
    input()
    
if howitem == "4":
    print('First item id:')
    fi = input()
    print('')
    print('First item quantity')
    fc = input()
    print('')
    print('First item nbt (optional):')
    fn = input()
    print('')
    print('Second item id:')
    si = input()
    print('')
    print('Second item quantity')
    sc = input()
    print('')
    print('Second item nbt (optional):')
    sn = input()
    print('')
    print('Third item id:')
    ti = input()
    print('')
    print('Third item quantity')
    tc = input()
    print('')
    print('Third item nbt (optional):')
    tn = input()
    print('')
    print('Fourth item id:')
    fi = input()
    print('')
    print('Fourth item quantity')
    fc = input()
    print('')
    print('Fourth item nbt (optional):')
    fn = input()
    print('')
    print('Crafted item:')
    ci = input()
    print('')
    print('Crafted item count')
    cc = input()
    print('')
    print('Crafted item nbt (optional):')
    cn = input()
    print('')
    print('')
    print('')
    if fn != "":
        fn = ',tag:' + fn
    if sn != "":
        sn = ',tag:' + sn
    if tn != "":
        tn = ',tag:' + tn
    if fn != "":
        fn = ',tag:' + fn
    if cn != "":
        cn = ',tag:' + cn
    print('')
    print('')
    print('')
    print('')
    print('First command:')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + ti +'",Count:' + tc + 'b' + tn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + fi +'",Count:' + fc + 'b' + fn + '}}] run summon item ~ ~ ~ {Item:{id:"minecraft:' + ci + '",Count:' + cc + 'b' + cn + '}}')
    print('')
    print('Second command (particles):')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + ti +'",Count:' + tc + 'b' + tn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + fi +'",Count:' + fc + 'b' + fn + '}}] run particle minecraft:cloud ~ ~ ~ 0 0 0 0.1 100')
    print('')
    print('Third command:')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + ti +'",Count:' + tc + 'b' + tn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + fi +'",Count:' + fc + 'b' + fn + '}}] run kill @e[type=item,distance=..1,nbt=!{Item:{id:"minecraft:' + ci +'",Count:' + cc + 'b' + cn + '}}] ')
    print('')
    print('Custom command (optional):')
    print('')
    print('execute at @e[type=item,nbt={Item:{id:"minecraft:' + fi + '",Count:' + fc + 'b' + fn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + si +'",Count:' + sc + 'b' + sn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + ti +'",Count:' + tc + 'b' + tn + '}}] if entity @e[type=item,distance=..1,nbt={Item:{id:"minecraft:' + fi +'",Count:' + fc + 'b' + fn + '}}] run (YOUR COMMAND HERE)')
    print('')
    print('')
    print('')
    print('')
    input()